### ISSUE TITLE
Créer une commande info de l'état réel du circuit

### ISSUE THREAD

**Issue by jncanches** [mika-nt28/Jeedom-ChauffeEau#32]
Je pense qu'il serait bien de pouvoir renseigner une info d'état réel du circuit d'alimentation du chauffe-eau. Par exemple, mon chauffe-eau est branché sur une sortie KNX (ca pourrait être une prise connectée, ça serait pareil), et si je fais une modification dans ma config pendant une phase de chauffe (par exemple à minuit alors que ma plage de chauffe est entre 22h et 6h), alors le widget va afficher le chauffe-eau comme étant éteint, alors qu'en fait il est physiquement alimenté. Du coup il y a une désynchronisation entre l'état réel du circuit et l'affichage du widget. Le souci se poserait aussi si on a par exemple un bouton physique de déclenchement manuel de la marche forcée: le chauffe eau serait alimenté alors que le widget affichera que non, et ce jusqu'au prochain début de la programmation.

cf les posts suivants 
https://www.jeedom.com/forum/viewtopic.php?f=143&t=22740&p=567393&hilit=chauffe+eau#p567352

https://www.jeedom.com/forum/viewtopic.php?f=143&t=22740&p=567393&hilit=chauffe+eau#p567359

**Comment by mika-nt28** [comment]
Pourquoi pas, surveiller l'etat de commande du chauffe-eau pour mettre a jour l'etat de gestion du plugin
Par exemple, 
On force le chauffe-eau par ca commande knx, et le plugin se met en marche forcé
